spring:
  application:
    name: TaskManager

  # config datasource
  datasource:
    url: jdbc:mysql://localhost:3307/task_manager_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # config jpa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # config flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3307/task_manager_db
    user: root
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          ssl:
            trust: smtp.gmail.com
          auth: 'true'
    host: smtp.gmail.com
    username: ming18380@gmail.com
    password: zzie dywd mrsf ccsf
    port: '587'

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

MMM:
  taskmanager:
    app:
      jwtSecret: XdLbqfOxFZkJ+tSAk3AeGw5pNUZJIIJmaM3RJl/RoIg=
      jwtExpirationMs: 86400000
      jwtRefreshExpirationMs: 604800000

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.flywaydb: DEBUG