### Variables
@baseUrl = http://localhost:8080/api/v1
@token = Bearer eyJhbGciOiJIUzI1NiJ9...
@projectId = 1
@taskId = 1

### GET tasks by project (Kanban)
GET {{baseUrl}}/projects/{{projectId}}/tasks?status=Todo&search=&page=0&size=20
Authorization: {{token}}
Content-Type: application/json

###

### GET tasks by project with status filter
GET {{baseUrl}}/projects/{{projectId}}/tasks?status=In Progress&page=0&size=10
Authorization: {{token}}

###

### GET task detail
GET {{baseUrl}}/tasks/{{taskId}}
Authorization: {{token}}

###

### GET my tasks
GET {{baseUrl}}/tasks/my-tasks
Authorization: {{token}}

###

### GET statistic by project
GET {{baseUrl}}/tasks/{{projectId}}/statistic
Authorization: {{token}}
